/* 002 — Modelo novo de comandas.
   O código (View/uExecute.dfm, rotina "Atualiza Tabelas") cria estas tabelas e campos, mas o banco do
   repositório ainda não os tinha. Comandos copiados do uExecute.dfm. */

SET SQL DIALECT 3;

ALTER TABLE MESAS ADD FK_COMANDA INTEGER;
ALTER TABLE MESAS ADD FK_USUARIO INTEGER;
ALTER TABLE MESAS ADD ATIVO VARCHAR(1);

CREATE TABLE COMANDA (
    CODIGO       INTEGER NOT NULL,
    FK_VENDEDOR  INTEGER,
    FK_EMPRESA   INTEGER,
    FK_MESA      INTEGER,
    DATA         DATE,
    SUBTOTAL     DECIMAL(15,2),
    DESCONTO     DECIMAL(15,2),
    ACRESCIMO    DECIMAL(15,2),
    TOTAL        DECIMAL(15,2),
    SITUACAO     VARCHAR(1)
);

CREATE TABLE COMANDA_ITENS (
    CODIGO      INTEGER NOT NULL,
    FK_COMANDA  INTEGER,
    FK_PRODUTO  INTEGER,
    QTD         DECIMAL(15,2),
    PRECO       DECIMAL(15,2),
    TOTAL       DECIMAL(15,2),
    SITUACAO    VARCHAR(1),
    IMPRIME     VARCHAR(1)
);

COMMIT;

ALTER TABLE COMANDA ADD CONSTRAINT PK_COMANDA PRIMARY KEY (CODIGO);
ALTER TABLE COMANDA ADD CONSTRAINT FK_COMANDA_1 FOREIGN KEY (FK_VENDEDOR) REFERENCES VENDEDORES (CODIGO) ON DELETE CASCADE;
ALTER TABLE COMANDA ADD CONSTRAINT FK_COMANDA_2 FOREIGN KEY (FK_EMPRESA) REFERENCES EMPRESA (CODIGO) ON DELETE CASCADE;
ALTER TABLE COMANDA ADD CONSTRAINT FK_COMANDA_3 FOREIGN KEY (FK_MESA) REFERENCES MESAS (CODIGO) ON DELETE CASCADE;
ALTER TABLE COMANDA_ITENS ADD CONSTRAINT PK_COMANDA_ITENS PRIMARY KEY (CODIGO);
ALTER TABLE COMANDA_ITENS ADD CONSTRAINT FK_COMANDA_ITENS_1 FOREIGN KEY (FK_COMANDA) REFERENCES COMANDA (CODIGO) ON DELETE CASCADE;
ALTER TABLE COMANDA_ITENS ADD CONSTRAINT FK_COMANDA_ITENS_2 FOREIGN KEY (FK_PRODUTO) REFERENCES PRODUTO (CODIGO) ON DELETE CASCADE;

COMMIT;
